defaults:  
  - _self_
_target_: transformers.TrainingArguments
output_dir: ${hydra:runtime.output_dir}/checkpoints
num_train_epochs: 3.0
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
eval_strategy: steps
seed: 42
load_best_model_at_end: true